[server]
headless = true
address = "127.0.0.1"
maxUploadSize = 20
maxMessageSize = 25
enableCORS = true
enableXsrfProtection = true
enableStaticServing = false

[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#2a78d6"
