[server]
headless = true
address = "127.0.0.1"
maxUploadSize = 20
maxMessageSize = 25
enableCORS = true
enableXsrfProtection = true
enableStaticServing = false

[client]
showErrorDetails = "none"
toolbarMode = "viewer"

[browser]
gatherUsageStats = false

[theme.light]
primaryColor = "#2a78d6"

[theme.dark]
primaryColor = "#78adff"
